spring.application.name=api
# Perfil activo
spring.profiles.active=dev

# Base de Datos (Docker inyectará estos valores)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=true
# Configuración de Jackson para JSON, que se vea bonito en las respuestas
spring.jackson.serialization.indent_output=true

# Integración FatSecret
fatsecret.client.id=${FATSECRET_CLIENT_ID}
fatsecret.client.secret=${FATSECRET_CLIENT_SECRET}
fatsecret.oauth.url=https://oauth.fatsecret.com/connect/token
fatsecret.api.url=https://platform.fatsecret.com/rest/server.api


# Integradcion de ExerciseDB
rapidapi.key=35941fc0a3msh0bf69ee34dbd7b9p1fb397jsn3ae17770b788
rapidapi.host=exercisedb.p.rapidapi.com
rapidapi.url=https://exercisedb.p.rapidapi.com/exercises
#Pexels
pexels.api.key=hL29F3ETMBDZHkW1wXbeEa9FMGoTpBzPT0H7DtSzTkz2ZxyuHCoqC4XC

# Configuración de JWT (El nombre debe coincidir con el de Docker)
# Configuración de JWT
jwt.secret=${JWT_SECRET}
# Cambiamos el nombre de la variable interna para evitar conflictos
jwt.expiration=${JWT_EXPIRATION:36000000} 

# CORS (Asegúrate de que esta línea termine correctamente)
app.cors.origins=*
#app.cors.origins=https://gymcrush-tfg.onrender.com


#GOOGLE LOGIN
google.client-id=765139895932-it22dhcqfe3mbbhgka7vuobea7no3sb5.apps.googleusercontent.com
#app.base-url=https://gymcrush-tfg.onrender.com